### ISSUE TITLE
license nit

### ISSUE THREAD

**Issue by isaacs** [jamestalmage/stack-utils#3]
Hi, obviously it's totally cool to pull node-tap's lib/stack.js into a standalone module, and I appreciate you doing that.

But, since this is based on that code, would you mind updating the license to include the copyright, as required by node-tap's ISC license?  Maybe something like this?

```
Copyright (c) James Talmage <james@talmage.io> (github.com/jamestalmage), Isaac Z. Schlueter <i@izs.me>, and Contributors

Extracted from code in node-tap http://www.node-tap.org/
```

I don't mean to be weird, and I'm definitely not upset and this is not borne out of frustration or conflict.  I'm only mentioning it because being in a new git repo means that the git history doesn't preserve the provenance of the code, and I like to maintain best practices for this sort of thing.

Changing to the MIT license is fine, it's functionally equivalent to ISC anyway.

Thanks :)

**Comment by jamestalmage** [comment]
Yep - no problem. I meant to ask you how you wanted me to handle attribution. 

The license is just the default from the yoeman generator I used, happy to switch to ISC if you prefer.

**Comment by jamestalmage** [comment]
@isaacs - fixed the attribution. Let me know if you would prefer switching to the ISC license.

**Comment by jamestalmage** [comment]
I would also happily to move this into https://github.com/tapjs if you would prefer to maintain more control over it.

**Comment by isaacs** [comment]
Awesome, thanks!

I'd really love for you to keep maintaining it, actually, if you don't mind.  But moving it into @tapjs probably makes sense.  I'll add you to the org.

**Comment by jamestalmage** [comment]
:+1: I don't mind at all!
